import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';
import toast from 'react-hot-toast';
import whiteLabelApiService from '../services/whiteLabelApiService';

const WhiteLabelContext = createContext();

export const useWhiteLabel = () => {
  const context = useContext(WhiteLabelContext);
  if (!context) {
    throw new Error('useWhiteLabel must be used within WhiteLabelProvider');
  }
  return context;
};

const DEFAULT_SETTINGS = {
  enabled: false,
  customDomain: '',
  companyName: 'AdCopySurge',
  customLogo: null,
  primaryColor: '#7C3AED',
  secondaryColor: '#A855F7',
  accentColor: '#10b981',
  hideOriginalBranding: false,
  removePoweredBy: false,
  customLoginPage: false,
  customEmailTemplate: false,
  sslEnabled: true,
  subdomainPrefix: 'app',
  favicon: null,
  reportHeaderLogo: null,
  reportFooterText: 'Generated by Your Agency Name',
  customReportTemplate: false,
  watermarkRemoval: false,
  customSupportEmail: '',
  customTermsUrl: '',
  customPrivacyUrl: '',
  // Preview mode
  previewMode: false,
  // Setup wizard progress
  setupStep: 0,
  setupCompleted: false
};

export const WhiteLabelProvider = ({ children }) => {
  const [settings, setSettings] = useState(() => {
    // Load from localStorage on initialization
    try {
      const saved = localStorage.getItem('whiteLabel-settings');
      return saved ? { ...DEFAULT_SETTINGS, ...JSON.parse(saved) } : DEFAULT_SETTINGS;
    } catch (error) {
      console.error('Failed to load white-label settings:', error);
      return DEFAULT_SETTINGS;
    }
  });

  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  // Load settings from backend on initialization
  useEffect(() => {
    const loadSettingsFromBackend = async () => {
      try {
        setIsLoading(true);
        
        // Check if backend API is available
        const apiHealth = await whiteLabelApiService.checkApiHealth();
        
        if (apiHealth.available) {
          // Try to load settings from backend
          const result = await whiteLabelApiService.loadSettings();
          
          if (result.success && result.data) {
            // Transform backend data to frontend format
            const backendSettings = {
              companyName: result.data.company_name || DEFAULT_SETTINGS.companyName,
              customDomain: result.data.custom_domain || DEFAULT_SETTINGS.customDomain,
              customSupportEmail: result.data.custom_support_email || DEFAULT_SETTINGS.customSupportEmail,
              primaryColor: result.data.primary_color || DEFAULT_SETTINGS.primaryColor,
              secondaryColor: result.data.secondary_color || DEFAULT_SETTINGS.secondaryColor,
              accentColor: result.data.accent_color || DEFAULT_SETTINGS.accentColor,
              hideOriginalBranding: result.data.hide_original_branding || DEFAULT_SETTINGS.hideOriginalBranding,
              removePoweredBy: result.data.remove_powered_by || DEFAULT_SETTINGS.removePoweredBy,
              customLoginPage: result.data.custom_login_page || DEFAULT_SETTINGS.customLoginPage,
              sslEnabled: result.data.ssl_enabled || DEFAULT_SETTINGS.sslEnabled,
              enabled: result.data.enabled || DEFAULT_SETTINGS.enabled,
              setupCompleted: result.data.setup_completed || DEFAULT_SETTINGS.setupCompleted
            };
            
            // Merge with localStorage settings and backend settings
            setSettings(prev => ({ ...prev, ...backendSettings }));
            console.log('Ἲ8 White-label settings loaded from backend');
          } else {
            console.log('Ἲ8 No backend settings found, using localStorage/defaults');
          }
        } else {
          console.log('Ἲ8 Backend API unavailable, using localStorage settings');
        }
      } catch (error) {
        console.error('Failed to load settings from backend:', error);
        // Continue with localStorage settings
      } finally {
        setIsLoading(false);
      }
    };
    
    // Only run once on mount
    loadSettingsFromBackend();
  }, []);

  // Persist settings to localStorage whenever they change
  useEffect(() => {
    try {
      localStorage.setItem('whiteLabel-settings', JSON.stringify(settings));
      console.log('Ἲ8 White-label settings saved to localStorage');
    } catch (error) {
      console.error('Failed to save white-label settings:', error);
    }
  }, [settings]);

  // Update a single setting
  const updateSetting = (key, value) => {
    setSettings(prev => ({
      ...prev,
      [key]: value
    }));
  };

  // Update multiple settings at once
  const updateSettings = (newSettings) => {
    setSettings(prev => ({
      ...prev,
      ...newSettings
    }));
  };

  // Reset to defaults
  const resetSettings = () => {
    setSettings(DEFAULT_SETTINGS);
    toast.success('White-label settings reset to defaults');
  };

  // Toggle preview mode
  const togglePreviewMode = () => {
    updateSetting('previewMode', !settings.previewMode);
  };

  // File upload handler for logos and favicons
  const uploadFile = async (file, type = 'logo') => {
    if (!file) return null;

    // Validate file
    const maxSize = 5 * 1024 * 1024; // 5MB
    if (file.size > maxSize) {
      throw new Error('File must be smaller than 5MB');
    }

    const allowedTypes = {
      logo: ['image/png', 'image/jpeg', 'image/jpg', 'image/svg+xml', 'image/webp'],
      favicon: ['image/x-icon', 'image/png', 'image/svg+xml'],
      reportLogo: ['image/png', 'image/jpeg', 'image/jpg', 'image/svg+xml', 'image/webp']
    };

    // If no specific type is provided, use general image validation
    const validTypes = allowedTypes[type] || ['image/png', 'image/jpeg', 'image/jpg', 'image/svg+xml', 'image/webp'];
    
    if (!validTypes.includes(file.type)) {
      throw new Error(`Invalid file type. Please use: ${validTypes.map(t => t.split('/')[1].toUpperCase()).join(', ')}`);
    }

    try {
      setIsLoading(true);
      
      // Convert to base64 for now (in production, upload to cloud storage)
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = (e) => resolve(e.target.result);
        reader.onerror = () => reject(new Error('Failed to read file'));
        reader.readAsDataURL(file);
      });
    } finally {
      setIsLoading(false);
    }
  };

  // Handle logo upload
  const handleLogoUpload = async (file) => {
    try {
      setIsLoading(true);
      
      // Check if backend API is available
      const apiHealth = await whiteLabelApiService.checkApiHealth();
      
      if (apiHealth.available) {
        // Use backend API
        const result = await whiteLabelApiService.uploadLogo(file);
        
        if (result.success) {
          updateSetting('customLogo', result.data.url);
          toast.success('Logo uploaded successfully!');
        } else {
          throw new Error(result.error);
        }
      } else {
        // Fallback to client-side processing
        const logoData = await uploadFile(file, 'logo');
        updateSetting('customLogo', logoData);
        toast.success('Logo uploaded successfully! (Note: Using local storage)');
      }
    } catch (error) {
      console.error('Logo upload failed:', error);
      toast.error(error.message);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  // Handle favicon upload
  const handleFaviconUpload = async (file) => {
    try {
      const faviconData = await uploadFile(file, 'favicon');
      updateSetting('favicon', faviconData);
      toast.success('Favicon uploaded successfully!');
    } catch (error) {
      console.error('Favicon upload failed:', error);
      toast.error(error.message);
      throw error;
    }
  };

  // Handle report logo upload
  const handleReportLogoUpload = async (file) => {
    try {
      const logoData = await uploadFile(file, 'reportLogo');
      updateSetting('reportHeaderLogo', logoData);
      toast.success('Report logo uploaded successfully!');
    } catch (error) {
      console.error('Report logo upload failed:', error);
      toast.error(error.message);
      throw error;
    }
  };

  // Validate domain
  const validateDomain = async (domain) => {
    try {
      setIsLoading(true);
      
      // Check if backend API is available
      const apiHealth = await whiteLabelApiService.checkApiHealth();
      
      if (apiHealth.available) {
        // Use backend API for domain validation
        const result = await whiteLabelApiService.validateDomain(domain);
        
        if (result.success) {
          console.log('✅ Domain validated:', domain);
          toast.success('Domain validated successfully!');
          return { valid: true, domain };
        } else {
          throw new Error(result.error);
        }
      } else {
        // Fallback to client-side validation
        const domainRegex = /^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.([a-zA-Z]{2,})$/;
        
        if (!domainRegex.test(domain)) {
          throw new Error('Invalid domain format');
        }
        
        // Simulate DNS check
        await new Promise(resolve => setTimeout(resolve, 800));
        
        console.log('✅ Domain validated (client-side):', domain);
        toast.success('Domain validated successfully! (Note: Using client-side validation)');
        return { valid: true, domain };
      }
    } catch (error) {
      console.error('Domain validation failed:', error);
      toast.error(error.message);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  // Test email sending
  const testEmail = async (email) => {
    try {
      setIsLoading(true);
      
      // Check if backend API is available
      const apiHealth = await whiteLabelApiService.checkApiHealth();
      
      if (apiHealth.available) {
        // Use backend API to send test email
        const result = await whiteLabelApiService.testEmail(email);
        
        if (result.success) {
          console.log('✉ Test email sent to:', email);
          toast.success(`Test email sent to ${email}`);
          return { success: true };
        } else {
          throw new Error(result.error);
        }
      } else {
        // Simulate sending email (fallback)
        await new Promise(resolve => setTimeout(resolve, 1000));
        console.log('✉ Test email simulated to:', email);
        toast.success(`Test email simulated to ${email} (backend unavailable)`);
        return { success: true };
      }
    } catch (error) {
      console.error('Failed to send test email:', error);
      toast.error('Failed to send test email');
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  // Setup wizard navigation
  const nextStep = () => {
    updateSetting('setupStep', Math.min(settings.setupStep + 1, 4));
  };

  const prevStep = () => {
    updateSetting('setupStep', Math.max(settings.setupStep - 1, 0));
  };

  const completeSetup = () => {
    updateSettings({
      setupCompleted: true,
      setupStep: 4
    });
    toast.success('White-label setup completed!');
  };

  // Memoize effective branding values to prevent infinite re-renders
  const effectiveBranding = useMemo(() => ({
    companyName: settings.companyName || 'AdCopySurge',
    logo: settings.customLogo || null,
    primaryColor: settings.primaryColor || '#7C3AED',
    secondaryColor: settings.secondaryColor || '#A855F7',
    customDomain: settings.customDomain || '',
    customSupportEmail: settings.customSupportEmail || '',
    showPoweredBy: !settings.removePoweredBy,
    // Always return these values regardless of enabled state
    enabled: settings.enabled || false,
    setupCompleted: settings.setupCompleted || false
  }), [settings]);

  // Get effective branding values (kept for backward compatibility)
  const getEffectiveBranding = () => effectiveBranding;

  // Save settings (for wizard completion)
  const saveSettings = async () => {
    try {
      setIsLoading(true);
      
      // Check if backend API is available
      const apiHealth = await whiteLabelApiService.checkApiHealth();
      
      if (apiHealth.available) {
        // Save to backend API
        const result = await whiteLabelApiService.saveSettings({
          company_name: settings.companyName,
          custom_domain: settings.customDomain,
          custom_support_email: settings.customSupportEmail,
          primary_color: settings.primaryColor,
          secondary_color: settings.secondaryColor,
          accent_color: settings.accentColor,
          hide_original_branding: settings.hideOriginalBranding,
          remove_powered_by: settings.removePoweredBy,
          custom_login_page: settings.customLoginPage,
          ssl_enabled: settings.sslEnabled
        });
        
        if (result.success) {
          // Also save to localStorage as backup
          localStorage.setItem('whiteLabel-settings', JSON.stringify(settings));
          console.log('✅ White-label settings saved to backend and localStorage');
          return { success: true };
        } else {
          throw new Error(result.error);
        }
      } else {
        // Fallback to localStorage only
        localStorage.setItem('whiteLabel-settings', JSON.stringify(settings));
        console.log('✅ White-label settings saved to localStorage (backend unavailable)');
        return { success: true };
      }
    } catch (error) {
      console.error('Failed to save white-label settings:', error);
      setError(error.message);
      throw error;
    } finally {
      setIsLoading(false);
    }
  };

  // Enable/disable preview mode
  const enablePreview = () => {
    updateSetting('previewMode', true);
    console.log('🎨 Preview mode enabled');
  };

  const disablePreview = () => {
    updateSetting('previewMode', false);
    console.log('🎨 Preview mode disabled');
  };


  // Check if minimum setup is complete
  const isMinimumSetupComplete = () => {
    return settings.enabled && 
           settings.companyName && 
           settings.primaryColor;
  };

  const value = {
    // Settings state
    settings,
    isLoading,
    error,
    
    // Settings actions
    updateSetting,
    updateSettings,
    resetSettings,
    saveSettings,
    
    // File uploads
    handleLogoUpload,
    handleFaviconUpload,
    handleReportLogoUpload,
    uploadFile,
    
    // Preview mode
    togglePreviewMode,
    enablePreview,
    disablePreview,
    
    // Setup wizard
    nextStep,
    prevStep,
    completeSetup,
    
    // Validation and testing
    validateDomain,
    testEmail,
    isMinimumSetupComplete,
    
    // Computed values
    effectiveBranding,
    getEffectiveBranding,
    
    // Constants
    DEFAULT_SETTINGS
  };

  return (
    <WhiteLabelContext.Provider value={value}>
      {children}
    </WhiteLabelContext.Provider>
  );
};